#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 taniguchi ryu
# SPDX-License-Identifier: BSD-3-Clause

import sys

def main():
    if len(sys.argv) < 2:
        print("使い方: ./count <単語>", file=sys.stderr)
        sys.exit(1)

    target_word = sys.argv[1] 
    total_count = 0

    for line in sys.stdin:
        total_count += line.count(target_word)
    
    print(total_count)

if __name__ == '__main__':
    main()
